### ISSUE TITLE
Github pages not enabled?

### ISSUE THREAD

**Issue by kylebarron** [stac-extensions/storage#12]
The README gives https://stac-extensions.github.io/storage/v1.0.0/schema.json as the current JSON Schema link, but that link doesn't resolve.

**Comment by matthewhanson** [comment]
Hey @kylebarron a v1.0 hasn't been released yet.  Hope to get the last issues finalized and published by end of week

**Comment by kylebarron** [comment]
Ah sorry, since the link existed on the homepage I just assumed it was meant to exist. No pressure; looking forward to testing it out in the future
