### ISSUE TITLE
storage:first_byte_latency as str?

### ISSUE THREAD

**Issue by lossyrob** [stac-extensions/storage#14]
storage:first_byte_latency is a string, but seems like it could be a numeric value in order to be more useful to users? Or perhaps specify a well formatted string, like `10m` or `1s` ... unclear if there's a standard string format we can point to that has time units of measure. Seems like this should be a float and always "seconds"...unless there's a specific use case for hour-long latency

**Comment by m-mohr** [comment]
Yes, maybe go with ISO 8601 durations? P1D for a day, for example.

**Comment by matthewhanson** [comment]
The field `storage:tier` already implies a latency based on the cloud provider and those values are published.

I think the best approach is to remove this for now and get a 1.0.0 version published, and we can add some of these other fields back in for a v2.0.0 if needed and they are defined a bit more.

**Comment by matthewhanson** [comment]
Removed
