### ISSUE TITLE
Document suggested platform names

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/storage#17]
The documentation for `storage:platform` links to a chapter about the platforms, but the values given there don't correspond to the values given in examples. What platform names should be used for common/popular platforms? This would improve interoperability and clients could link to more useful information if a common set of values would have been agreed on.

**Comment by duckontheweb** [comment]
I ran into this as I was implementing this extension in PySTAC for stac-utils/pystac#734. The JSON schema [uses an enum](https://github.com/stac-extensions/storage/blob/4944d586547fa561569eb696cb3d0ff1589115b5/json-schema/schema.json#L95-L108) but it's not clear from the README that you have to use one of these values.
