### ISSUE TITLE
How to identify other storage providers?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/storage#22]
Is there a way to identify other storage providers? The extension seems pretty biased right now towards US services, listing none in the EU for example, only one in China. Using OTHER doesn't let you identify the storage provider and the regions and tiers then are pretty disconnected and not very useful.

**Comment by MathewNWSH** [comment]
Hello,

I totally identify with this issue through my use case. I am a developer working with data from the Copernicus program, stored on the CREODIAS cloud, which is part of the Copernicus Data Space Ecosystem.
I believe that for such large and open initiatives like CDSE, this deserves to be emphasized in a form other than "OTHER". At this moment, using a value other than those available causes a validation error for the item.

- The importance of CDSE's availability among the selected options underscores the fact that it is the official storage for Sentinel mission data.

**Regarding Cloud Provider Storage Tiers in the case of CDSE, there is only a standard tier, but there is no minimum duration included.**

**Comment by fmigneault** [comment]
Same issue for our use case. We use platform-specific hosted data. `storage:platform: OTHER` seems like the appropriate value, but then users do not have a reference of where/what that "OTHER" is located/is.

**Comment by m-mohr** [comment]
I just looked at the extension again and the storage:platform default value is OTHER, so the field doesn't need to be provided so the weird "OTHER" is gone. 

Currently, the other pre-defined enum values are also not used to enforce specific values for the other fields so having the enum is a bit useless. 

I'm wondering whether we should remove the enum and make it free-text. For the providers where we want to validate specific values, we should create specific sub-schemas for individual proviers (or separate extensions that build on top of storage?)

**Comment by m-mohr** [comment]
Please review the PR for version 2 that is meant to solve this issue: #24
