### ISSUE TITLE
alternate locations

### ISSUE THREAD

**Issue by matthewhanson** [stac-extensions/storage#8]
There's a couple use cases for defining alternate URLs for an asset. This could be a different URL that ultimately points to the same data (an s3 URL as well as an http URL), or could be an actual mirror of the data stored in an alternate location.

See https://github.com/radiantearth/stac-spec/issues/997

Having to specify multiple assets is not ideal, as most of the information will be the same in both cases (if it's a mirrored copy or just an alternate URL), and is difficult for clients to parse and determine which assets are in fact the same.  The examples provided in this extension uses different assets for different cloud provider versions: https://github.com/stac-extensions/storage/blob/main/examples/example-naip.json

When looking through the existing asset fields in core as well as extensions, the only ones that should vary are the fields proposed in this extension, providing additional hrefs, bucket locations, regions, etc.

I propose that storage become a `location` object, and `locations` is an array within an asset:

## Asset Fields

| Field Name  | Type   | Description |
| ----------- | ------ | ----------- |
| storage:locations | [Location Object] | (REQUIRED) An array of one more location objects providing information on where the data is stored and how to access.

### Location Object

| Field Name  | Type   | Description |
| ----------- | ------ | ----------- |
| platform              | string    | (REQUIRED) The [cloud provider](#providers) where data is stored |
| href | string | A complete URL of the appropriate type (e.g., http://, s3://) to the asset |
| manager               | string    | The entity in charge of managing the data. |
| region                | string    | (REQUIRED) The region where the data is stored. Relevant to speed of access and inter region egress costs (as defined by PaaS provider) |
| bucket                | string    | The bucket for the asset, used along with object path |
| object_path           | string    | The object_path for the asset, used along with bucket |
| requester_pays        | bool      | (REQUIRED) Is the data requester pays or is it data manager/cloud provider pays |
| tier                  | string    | The title for the tier type (as defined by PaaS provider) |
| tier_duration         | integer   | Minimum storage duration (in days) required before additional fees |
| date_stored           | string    | Date and time the corresponding asset placed into the current storage tier (relevant for tier_duration > 0). Format is RFC 3339. |
| first_byte_latency    | string    | approximate time unit (milliseconds, minutes or hours) for accessing first byte of data |

As an example:

```
assets = {
    "B01": {
        "title": "Band 1 (coastal)",
        "type": "image/tiff; application=geotiff; profile=cloud-optimized",
        "roles: [
            "datta"
        ],
        "href": "https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/58/W/DB/2021/5/S2A_58WDB_20210525_0_L2A/B01.tif"
        "storage:locations": [
            {
                "platform": "AWS",
                "href": "s3://sentinel-cogs/sentinel-s2-l2a-cogs/58/W/DB/2021/5/S2A_58WDB_20210525_0_L2A/B01.tif"
                "region": "us-west-2",
                "requester_pays": false
            }
        ]
    }
}
```

Note that core STAC still requires an `href` at the asset level, and this should be the nominal href, perhaps even duplicated in the first location object.

**Comment by gadomski** [comment]
In general, 👍🏽 to the concept -- if the underlying data are the same, then the links should be in the same asset. A couple of questions:

- (you've hinted at this one already) How do we handle assets where _every_ possible access mode requires a `Location` object, such that the bare asset `href` is not enough to get the data? My initial thought is to maybe specify in the storage extension "if the `href` alone is not enough to access the data, the item _shall_ have a `Location` in its `storage:locations` with an identical `href` containing the necessary connection information" or something like that.
- Not all storage locations would have a `platform`, e.g. I could see wanting to provide http and ftp access alternatives (e.g. 3DEP if you don't want to go through Amazon).
- Not everyone uses "bucket", e.g. Azure calls them "containers". We'll need to document how to map each cloud provider's data model onto these `Location` objects.

**Comment by duckontheweb** [comment]
I know this has been discussed a bit on Gitter and other channels, but I wanted to also raise the question of whether the definition for alternate locations should be part of this extension or a separate extension. 

There could be a case for providing alternate asset locations that are not related to cloud storage. One example would be providing both HTTP and FTP links for the same resource. The difficulty with this is that the way we define an alternative location would obviously be very different for something like an FTP link (which would just be an alternate `"href"`) vs. the cloud storage parameters defined here. 

One way to handle this in a separate extension might be to have that extension define something like an `"alternate_locations"` that is an array of objects. Those objects would then need to contain whatever Asset properties are needed to fully define the alternate location (`"href"` in the case of an FTP location, or the `"storage:*"` properties in the case of a cloud storage location), but the alternate location extension would not specifically require any properties of its own.

I'm wondering what people think about this alternative and whether it seems preferable to defining alternate locations within the Storage Extension.

**Comment by gadomski** [comment]
> I may be off-base on this, but it seems like this case could be represented through the typical "href" property, so maybe wouldn't even need to be covered by this extension?

Agreed.

**Comment by matthewhanson** [comment]
I had thought about the alternate_locations being a different extension, but since this storage extension also includes an `href`, the fields in this extension are the only ones that would ever be referenced in an alternate_locations array.

But I guess a nice thing about it being another extension is then you can use all these storage fields at the assets top-level without having to include an array, which is nice.

Going to close this and create a new extension for alternate locations
